### PR TITLE
Mosaic added to games

### PR DESCRIPTION
**Pull request by kohend**
Adding a game similar to mines to the collection

### CODE REVIEW

**Comment by mquevill** [comment]
Now merged into upstream: https://git.tartarus.org/?p=simon/puzzles.git;a=commit;h=0377184510629b15814e3fd6c9f0f1d9e58b9209

**Comment by chrisboyle** [comment]
Thank you very much for the new game, and sorry I didn't look at it sooner! I've now merged from upstream including this game, and it will be in the next release.

**Comment by kohend** [comment]
When is the next release planned?

**Comment by chrisboyle** [comment]
No specific date, but I'm hoping to have a beta ready soon once I've done #377, fixed the app icon for new requirements, and any other minor things that I notice. After that it depends what people find from the beta, but definitely before late July, because that's the deadline for the Play Store Data Safety Form, and the new version can simply say no data is collected or transmitted, whereas with current releases it's more debatable because of the email feedback mechanism.

**Pull request closed without merging**
