### PR TITLE
Fixed pencil marks in solo and unequal

### PR DESCRIPTION
**Pull request by sullerandras**
I made pencil marks "fixed" in solo and unequal. Similar to the improvement request described in this issue: https://github.com/chrisboyle/sgtpuzzles/issues/260

Do not accept this pull request yet. It is work in progress.
How to make this option a custom setting? Perhaps a per game setting, default to off. Can you give me some guidance? Thanks.

p.s.: I am using Mac OS X 10.9 and was able to make the project work without any issues. Great job!

### CODE REVIEW

**Comment by chrisboyle** [comment]
On 2 August 2015 at 09:58, Andras Suller <notifications@github.com> wrote:
> I made pencil marks "fixed" in solo and unequal. Similar to the improvement
> request described in this issue: https://github.com/chrisboyle/sgtpuzzles/issues/260
>
> Do not accept this pull request yet. It is work in progress.
> How to make this option a custom setting? Perhaps a per game setting,
> default to off. Can you give me some guidance? Thanks.

I've just tried it; it looks good to me, thanks. :-) I'm CCing Simon
in case he has any thoughts about merging this upstream.

Personally I'd be tempted to make this default-on, but I don't know if
I've missed some advantage of the current behaviour? It could at least
be buried on the "advanced" screen ("display and keyboard").

For a per-game checkbox, the UI is easy (grep -ri bridges_?show_?h for
an example), but this might actually be the first time that an option
needs passing down to C, rather than messing with information that's
already being sent to it / received from it. Again this is
upstream-relevant, as Simon's mentioned the possibility of a settings
mechanism before where there currently isn't one.

For a temporary Android-only solution, I would perhaps add native
GameView.setFixedPencilMarks(boolean) (implement it in android.c),
called from somewhere like rebuildBitmap() before the redraw. You
should also call it when the setting changes during play; see
GamePlay.onSharedPreferenceChanged(). On the C end I'd probably hack
another android-specific method into struct game (next to e.g.
android_cursor_visibility) that most games would ignore. It feels like
there might be a better way to do those things though, even absent an
upstream settings mechanism. Open to suggestions. :-)

-- 
Chris Boyle
https://chris.boyle.name/

**Comment by chrisboyle** [comment]
> On 2 August 2015 at 09:58, Andras Suller <notifications@github.com> wrote:
>> I made pencil marks "fixed" in solo and unequal. Similar to the
>> improvement request described in this issue:
>> https://github.com/chrisboyle/sgtpuzzles/issues/260

Chris Boyle <chris@boyle.name> wrote:
> I've just tried it; it looks good to me, thanks. :-) I'm CCing Simon
> in case he has any thoughts about merging this upstream.

If I'm understanding rightly, the change makes the pencil mark for each
possible digit appear at a fixed location in the cell, so that (e.g. in
ordinary 3x3 Sudoku) the 2 is always at top-centre and the 7 always
bottom-left?

This has been suggested a couple of times before, yes. I would be happy
to accept a patch upstream which made it happen on a conditional basis
(enabled via one of my hacky configuration environment variables, in the
absence of the proper per-user config system that you mention I've still
never got round to :-), but I wouldn't be happy with making it the
default. (Downstreams, of course, are welcome to disagree with me about
the right defaults.)

The reason why I wouldn't want it to be the default is because it forces
the pencil marks to be smaller. With the current system, the font size
used for pencil marks is scaled depending on how many marks have to
squeeze into the current square, so that if you only have two or three
in a square then you get an actually legible font, and it's only if you
try to put _all possible numbers_ into your pencil-marked square that
the font shrinks right down to unreadable-3-pixel mode. Whereas if you
fix the pencil-mark positions for each digit, I think you would also
have to fix the font size at always-unreadably-small even in cases where
there would otherwise be space to make it larger.

Perhaps on modern Android phones with their terrifyingly high DPI, this
is less of a concern. But on the desktop screen resolutions I still play
at, it is a concern! :-)

Cheers,
Simon

-- 
import hashlib; print (lambda p,q,g,y,r,s,m: m if (lambda w:(pow(g,int(hashlib.
 sha1(m).hexdigest(),16)*w%q,p)*pow(y,r*w%q,p)%p)%q)(pow(s,q-2,q))==r else "!"
 )(0xb80b5dacabab6145, 0xf70027d345023, 0x7643bc4018957897, 0x11c2e5d9951130c9,
 0xa54d9cbe4e8ab, 0x746c50eaa1910, "Simon Tatham <anakin@pobox.com>")

**Comment by sullerandras** [comment]
> If I'm understanding rightly, the change makes the pencil mark for each
> possible digit appear at a fixed location in the cell, so that (e.g. in
> ordinary 3x3 Sudoku) the 2 is always at top-centre and the 7 always
> bottom-left?

Yes, that is correct.

> This has been suggested a couple of times before, yes. I would be happy
> to accept a patch upstream which made it happen on a conditional basis
> (enabled via one of my hacky configuration environment variables, in the
> absence of the proper per-user config system that you mention I've still
> never got round to :-), but I wouldn't be happy with making it the
> default. (Downstreams, of course, are welcome to disagree with me about
> the right defaults.)

Wow, hacky config variables :)
How can I make a patch for the upstream? Is it also on github?

> The reason why I wouldn't want it to be the default is because it forces
> the pencil marks to be smaller. With the current system, the font size
> used for pencil marks is scaled depending on how many marks have to
> squeeze into the current square, so that if you only have two or three
> in a square then you get an actually legible font, and it's only if you
> try to put _all possible numbers_ into your pencil-marked square that
> the font shrinks right down to unreadable-3-pixel mode. Whereas if you
> fix the pencil-mark positions for each digit, I think you would also
> have to fix the font size at always-unreadably-small even in cases where
> there would otherwise be space to make it larger.

Yes, in fixed pencil mode the font would always be the smallest. But for me the position of the number helps a lot more than the font size.

**Comment by chrisboyle** [comment]
> How can I make a patch for the upstream? Is it also on github?

No, but it is a git repository:
```
git clone git://git.tartarus.org/simon/puzzles.git
```
There is [extensive developer documentation](http://www.chiark.greenend.org.uk/~sgtatham/puzzles/devel/) from Simon that I recommend reading.

**Pull request closed without merging**
