### PR TITLE
Improved readability ...

### PR DESCRIPTION
**Pull request by yashpalgoyal1304**
... of plaintext rendering of game for instructions

Ref for screenshots: https://github.com/chrisboyle/sgtpuzzles/issues/262#issuecomment-944471969

i was not able to test it since i dont have access to my android device. so, can someone please test the apk from this job and share their findings here??

### CODE REVIEW

**Comment by yashpalgoyal1304** [comment]
target/upstream destination: https://www.chiark.greenend.org.uk/~sgtatham/puzzles/doc/blackbox.html#blackbox

**Comment by lishaoxia1985** [comment]
I have written this By html5.✌(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)✌

**Comment by yashpalgoyal1304** [comment]
@lishaoxia1985 hmm, what? and how's it related to this 😅

**Comment by lishaoxia1985** [comment]
Like this, You can look at my branch, I'm a beginner, so it has more bugs. I split the android frontend and backend, now upgrade with the puzzles master easily.

**Comment by yashpalgoyal1304** [comment]
» _"Like this, (image)"_
oh, u meant that u solved the issue i was trying to address using an image via html5. am i right?? 
if so, then see my comment at: https://github.com/chrisboyle/sgtpuzzles/issues/262

» _"You can look at my branch"_
link?

» _"split the android front/backend, for easy upgrades"_
wow, super nice. 

» _"I'm a beginner, so it has more bugs."_
will u consider trying to break it down and maybe consider posting small pulls here?? that is, if the ppl here agree to 🤔

**Comment by lishaoxia1985** [comment]
No picture, in html, you can use label <table> <tr> <td> and "CSS", you can look at this:
https://github.com/lishaoxia1985/sgtpuzzles/blob/master/app/src/main/assets/en/blackbox.html

**Comment by yashpalgoyal1304** [comment]
ahww, css formated table, niiice. it looked soo much like a screenshot image.
awesome quality work with theming and css :+1:

some thoughts on it:
* umh, not putting u down or anyth, but it takes much more amount and lines in code, aint it. 
* and so, do u consider that the extra theming is worth the extra efforts?? 
* considering that the same css will still not be applicable as it is across the other game's tutorial if needed.
* i totally understand if it was for hobby and trying out stuff i.e. for concept stage  
but do u think it's suitable for deployement to masses as well?
* what do u say?

**Comment by yashpalgoyal1304** [comment]
hi @chrisboyle 
can u check this one?

**Comment by chrisboyle** [comment]
Just for future reference the docs are generated from `app/src/main/assets-sources/puzzles.but` with the command (run in assets-sources) `make -f Makefile.doc androiddocs` - but I've done all that this time

**Pull request merged**
